/** English chrome for the four AI tools. */

export const AI_UI = {
  hub: 'AI tools',
  intro: 'Live tools only. Each one says what it checks and what it will not do.',
  empty: 'No checks are available yet.',
  emptyBody: 'When a check is turned on, it will appear here.',
  start: 'Start a check',
  preview: 'Preview',
  staffPreview: 'Staff preview',
  unavailableTitle: 'Not available',
  unavailable: 'This check is not available.',
  upload: 'Upload',
  choose: 'Choose a file',
  fileHint: 'PDF, text, CSV, spreadsheet, or document. 15 MB max.',
  run: 'Run',
  running: 'Running',
  will: 'Will',
  willNot: 'Will not',
  allTools: 'All tools',
  prior: 'Prior notes',
  priorEmpty: 'No earlier checks yet. Run one when you are ready.',
  delete: 'Delete',
  findings: 'Findings',
  metrics: 'From your file',
  redFlags: 'Red flags',
  questions: 'Questions',
  sources: 'Sources',
  dated: 'Dated',
  status: 'Status',
  step: 'Step',
  queued: 'Queued',
  reading: 'Reading',
  checking: 'Checking',
  writing: 'Writing',
  ready: 'Ready',
  failed: 'Could not finish',
  intake: 'Intake',
  draft: 'Draft',
  done: 'Done',
  loadError: 'Could not load this tool. Retry.',
  retry: 'Retry',
  listError: 'Could not load the tool list. Retry.',
  loadingTools: 'Loading tools',
} as const

/** Per-run acknowledgement. Not stored. The longer tool consent stays separate. */
export const AI_OUTPUT_ACK =
  'I understand this is AI output, not legal, financial or investment advice.'
