/**
 * On-page legal copy for the four AI tools.
 * English banners, will and will-not lines, consent, and footers
 * follow the 2026-09-30 legal draft.
 * Pricing English uses the product name Pricing sense-check.
 */
import {
  AI_TOOL_NAMES,
  type AiToolKey,
} from '../../supabase/functions/_shared/ai_tools.ts'

export const SHARED_WILL_NOT = [
  'Give legal, financial, investment, tax or accounting advice.',
  'Recommend buying, selling or holding anything, or make any offer or solicitation.',
  'Act as a CMA-authorised person or replace a licensed adviser.',
  'Guarantee that its output is accurate, complete or current.',
] as const

export const SHARED_FOOTER =
  'Generated by AI on [DATE] from your inputs and public sources only. It may be wrong, incomplete or out of date. It is not legal, financial, investment, tax or accounting advice, is not an activity authorised by the Capital Market Authority, and is not a recommendation, offer or solicitation. Verify with licensed advisers before you act. Provided by [BA ENTITY], CR [CR], under the Board Arabia Terms [TERMS LINK]. Governed by the laws of the Kingdom of Saudi Arabia.'

export const SHARED_CONSENT =
  'I understand this tool uses AI, may be wrong or out of date, and is not legal, financial, investment, tax or accounting advice or a CMA-authorised activity. I will verify the output with licensed advisers and I am responsible for any decision I make. I have the right to share anything I upload, it contains no inside information, and I accept that it is processed under the Privacy Notice [PRIVACY LINK] in line with the Saudi PDPL, kept for [RETENTION DAYS] days and deletable by me at any time. I agree to the Terms [TERMS LINK], including the limitation of liability, governed by Saudi law.'

type ToolCopy = {
  title: string
  banner: string
  will: readonly string[]
  willNot: readonly string[]
  consentLead: string
  footerLead: string
}

const CFO: ToolCopy = {
  title: AI_TOOL_NAMES.cfo_check,
  banner:
    'An AI first read of your accounts or model. It flags runway, margins and red flags and suggests questions for your finance team. It is not accounting, audit or financial advice.',
  will: [
    'Read the accounts or model you upload.',
    'Estimate runway and margins from your figures.',
    'Flag possible red flags and inconsistencies.',
    'Suggest questions to ask your CFO or auditor.',
  ],
  willNot: [
    'Audit, review or certify accounts, or check them against IFRS or SOCPA standards.',
    'Verify that your figures are true.',
  ],
  consentLead:
    'I own or am authorised to share these financials, and I will not upload a listed company\'s non-public information.',
  footerLead: 'AI CFO check. A first read only, based on the figures you provided. Not an audit or accounting opinion.',
}

const TERM: ToolCopy = {
  title: AI_TOOL_NAMES.term_sheet_review,
  banner:
    'An AI read of a term sheet. It flags terms that look unusual compared with common market practice so you know what to ask. It is not legal or investment advice.',
  will: [
    'Summarise the key terms in plain words.',
    'Flag terms that look unusual against general market practice.',
    'Suggest questions for your lawyer.',
  ],
  willNot: [
    'Tell you whether to sign, invest or negotiate a term.',
    'Give a legal opinion or check enforceability under any law.',
  ],
  consentLead:
    'I am allowed to share this term sheet, including under any confidentiality obligation, and I will not upload a listed company\'s non-public information.',
  footerLead:
    'Term sheet review. "Market practice" means general patterns in public sources, not a legal opinion or a view on whether to invest.',
}

const PRICING: ToolCopy = {
  title: AI_TOOL_NAMES.pricing_sense_check,
  banner:
    'An AI comparison of an asking price with public comparables and reported regional deals. It is a sense-check for your own thinking, not a price opinion, fairness opinion or investment advice.',
  will: [
    'Compare the asking figure with public comparables and reported regional deals.',
    'Show the ranges and sources it used.',
    'Note the main gaps in the comparison.',
  ],
  willNot: [
    'Give a price opinion, price target or fairness opinion.',
    'Say whether a price is right or whether to invest.',
    'Use private deal data or non-public information.',
  ],
  consentLead:
    'I understand this is not a price opinion by a Taqeem-accredited valuer or a CMA-authorised person, and I will not rely on it to price, buy or sell any security.',
  footerLead:
    'Pricing sense-check. Comparables and deal data come from public sources and may be incomplete or stale. Not a price opinion or investment recommendation.',
}

const DEAL: ToolCopy = {
  title: AI_TOOL_NAMES.deal_readiness,
  banner:
    'This is not legal, financial or investment advice. It is an indicative first read of a real estate teaser or information memorandum, limited to title and escrow, foreign ownership, White Land, and gaps the document leaves open.',
  will: [
    'Read the teaser or information memorandum you upload.',
    'Note the title and escrow path only when the document states them.',
    'Note foreign ownership only when the document states it.',
    'Flag White Land wording that appears in the document.',
    'List gaps where the document is silent.',
  ],
  willNot: [
    'Invent a yield, a comparable, or a counterparty name.',
    'Say whether the title is clear, whether a foreign buyer may own the asset, or whether a White Land fee is due.',
    'Say what the asset is worth or whether to go ahead.',
  ],
  consentLead:
    'I am allowed to share this teaser or information memorandum, including where it is confidential.',
  footerLead:
    'Deal readiness memo. Indicative only. Where the document is silent, this note says Not stated in the document. It does not state a yield, a comparable, or a counterparty name.',
}

const MARKET: ToolCopy = {
  title: AI_TOOL_NAMES.market_brief,
  banner:
    'An AI brief on entering the Saudi market: licences, local partner rules, Saudization and incentives, from public sources. Rules change often. It is not legal or tax advice.',
  will: [
    'Outline common licences, foreign ownership and local partner points, Saudization (Nitaqat) and incentives for your sector.',
    'Link the public sources it used.',
    'List questions for a Saudi lawyer and MISA.',
  ],
  willNot: [
    'Confirm what applies to your specific case.',
    'Replace a licensed Saudi lawyer, tax adviser or the relevant government authority.',
  ],
  consentLead:
    'I understand Saudi rules change often and this brief may be out of date, and I will confirm requirements with a licensed Saudi lawyer and the relevant authority.',
  footerLead:
    'Saudi market entry brief. Based on public sources as at [DATE]. Confirm current rules with a licensed Saudi lawyer and the relevant authority.',
}

const TOOLS: Record<AiToolKey, ToolCopy> = {
  cfo_check: CFO,
  market_brief: MARKET,
  term_sheet_review: TERM,
  pricing_sense_check: PRICING,
  deal_readiness: DEAL,
}

export const AI_TOOL_CARD_LINES: Record<AiToolKey, string> = {
  cfo_check: 'A first read of accounts or a model. Not accounting or audit.',
  market_brief: 'A sourced brief on entering the Saudi market. Not legal or tax advice.',
  term_sheet_review: 'A read of a term sheet against common market practice. Not legal advice.',
  pricing_sense_check: 'A comparison with public comparables. General and educational only.',
  deal_readiness: 'A first read of a teaser or information memorandum. Indicative only.',
}

export const DEAL_ACCEPT =
  '.pdf,.txt,.docx,application/pdf,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document'

export function dealFileHint(days: number): string {
  return `PDF, text, or document. 15 MB max. Confidential. Deleted automatically after ${days} days.`
}

export function dealUploadNote(days: number): string {
  return `Confidential upload. The file is processed under the Saudi PDPL. Uploads and this memo use the existing AI tools retention and are deleted automatically after ${days} days. The default is 30 days. You can delete them earlier.`
}

export function toolTitle(tool: AiToolKey): string {
  return TOOLS[tool].title
}

export type LegalSlots = {
  entity: string
  cr: string
  provider: string
  privacy: string
  terms: string
  retentionDays: number
  date: string
}

export function fillLegal(text: string, slots: LegalSlots): string {
  return text
    .split('[BA ENTITY]').join(slots.entity)
    .split('[CR]').join(slots.cr)
    .split('[AI PROVIDER]').join(slots.provider)
    .split('[PRIVACY LINK]').join(slots.privacy)
    .split('[TERMS LINK]').join(slots.terms)
    .split('[RETENTION DAYS]').join(String(slots.retentionDays))
    .split('[DATE]').join(slots.date)
}

export type RenderedToolCopy = {
  title: string
  banner: string
  will: readonly string[]
  willNot: readonly string[]
  consent: string
  footerLead: string
  footerShared: string
  footer: string
}

/** English copy only. A leftover language argument is ignored. */
export function renderToolCopy(tool: AiToolKey, langOrSlots: 'en' | LegalSlots, maybeSlots?: LegalSlots): RenderedToolCopy {
  const slots = typeof langOrSlots === 'string' ? maybeSlots : langOrSlots
  if (!slots) {
    throw new Error('AI tool copy needs legal slots')
  }
  const block = TOOLS[tool]
  const lead = fillLegal(block.consentLead, slots)
  const core = fillLegal(SHARED_CONSENT, slots)
  const footerLead = fillLegal(block.footerLead, slots)
  const footerShared = fillLegal(SHARED_FOOTER, slots)
  return {
    title: block.title,
    banner: fillLegal(block.banner, slots),
    will: block.will,
    willNot: [...block.willNot, ...SHARED_WILL_NOT],
    consent: `${lead} ${core}`,
    footerLead,
    footerShared,
    footer: `${footerLead} ${footerShared}`,
  }
}

export function toolCopySource(tool: AiToolKey): ToolCopy {
  return TOOLS[tool]
}
