/**
 * On-page legal copy for the four AI tools.
 * English and Arabic banners, will and will-not lines, consent, and footers
 * follow the 2026-09-30 legal draft. Will and will-not bullets are English in
 * that draft, so both languages show those lines as written.
 * Pricing English uses the product name Pricing sense-check.
 */
import {
  AI_TOOL_NAMES,
  type AiToolKey,
} from '../../supabase/functions/_shared/ai_tools.ts'

export const SHARED_WILL_NOT = [
  'Give legal, financial, investment, tax or accounting advice.',
  'Recommend buying, selling or holding anything, or make any offer or solicitation.',
  'Act as a CMA-authorised person or replace a licensed adviser.',
  'Guarantee that its output is accurate, complete or current.',
] as const

export const SHARED_FOOTER = {
  en: 'Generated by AI on [DATE] from your inputs and public sources only. It may be wrong, incomplete or out of date. It is not legal, financial, investment, tax or accounting advice, is not an activity authorised by the Capital Market Authority, and is not a recommendation, offer or solicitation. Verify with licensed advisers before you act. Provided by [BA ENTITY], CR [CR], under the Board Arabia Terms [TERMS LINK]. Governed by the laws of the Kingdom of Saudi Arabia.',
  ar: 'أُعدّ هذا التقرير بالذكاء الاصطناعي بتاريخ [DATE] بناءً على مدخلاتك ومصادر عامة فقط. قد يكون خاطئاً أو ناقصاً أو غير محدّث. ولا يُعدّ استشارة قانونية أو مالية أو استثمارية أو ضريبية أو محاسبية، ولا نشاطاً مرخّصاً من هيئة السوق المالية، ولا توصية أو عرضاً أو دعوة. تحقّق مع مستشارين مرخّصين قبل اتخاذ أي قرار. مقدَّم من [BA ENTITY]، سجل تجاري رقم [CR]، وفق شروط بورد أرابيا [TERMS LINK]. يخضع لأنظمة المملكة العربية السعودية.',
} as const

export const SHARED_CONSENT = {
  en: 'I understand this tool uses AI, may be wrong or out of date, and is not legal, financial, investment, tax or accounting advice or a CMA-authorised activity. I will verify the output with licensed advisers and I am responsible for any decision I make. I have the right to share anything I upload, it contains no inside information, and I accept that it is processed under the Privacy Notice [PRIVACY LINK] in line with the Saudi PDPL, kept for [RETENTION DAYS] days and deletable by me at any time. I agree to the Terms [TERMS LINK], including the limitation of liability, governed by Saudi law.',
  ar: 'أُقرّ بأن هذه الأداة تعمل بالذكاء الاصطناعي، وقد تكون نتائجها خاطئة أو غير محدّثة، وأنها ليست استشارة قانونية أو مالية أو استثمارية أو ضريبية أو محاسبية ولا نشاطاً مرخّصاً من هيئة السوق المالية. سأتحقق من النتائج مع مستشارين مرخّصين، وأتحمّل مسؤولية أي قرار أتخذه. أُقرّ بأن لديّ الحق في مشاركة ما أرفعه، وأنه لا يتضمن معلومات داخلية، وأوافق على معالجته وفق إشعار الخصوصية [PRIVACY LINK] بما يتوافق مع نظام حماية البيانات الشخصية، وحفظه لمدة [RETENTION DAYS] يوماً مع إمكانية حذفه في أي وقت. وأوافق على الشروط [TERMS LINK] بما فيها حدود المسؤولية، وتخضع لأنظمة المملكة العربية السعودية.',
} as const

type Lang = 'en' | 'ar'

type ToolCopy = {
  title: Record<Lang, string>
  banner: Record<Lang, string>
  will: readonly string[]
  willNot: readonly string[]
  consentLead: Record<Lang, string>
  footerLead: Record<Lang, string>
}

const CFO: ToolCopy = {
  title: { en: AI_TOOL_NAMES.cfo_check, ar: 'الفحص المالي بالذكاء الاصطناعي' },
  banner: {
    en: 'An AI first read of your accounts or model. It flags runway, margins and red flags and suggests questions for your finance team. It is not accounting, audit or financial advice.',
    ar: 'قراءة أولية بالذكاء الاصطناعي لحساباتك أو نموذجك المالي. تُبرز مدة التشغيل المتبقية والهوامش ونقاط الخطر، وتقترح أسئلة لفريقك المالي. ليست استشارة محاسبية أو تدقيقاً أو استشارة مالية.',
  },
  will: [
    'Read the accounts or model you upload.',
    'Estimate runway and margins from your figures.',
    'Flag possible red flags and inconsistencies.',
    'Suggest questions to ask your CFO or auditor.',
  ],
  willNot: [
    'Audit, review or certify accounts, or check them against IFRS or SOCPA standards.',
    'Verify that your figures are true.',
  ],
  consentLead: {
    en: 'I own or am authorised to share these financials, and I will not upload a listed company\'s non-public information.',
    ar: 'أملك هذه البيانات المالية أو مخوَّل بمشاركتها، ولن أرفع أي معلومات غير معلنة لشركة مدرجة.',
  },
  footerLead: {
    en: 'AI CFO check. A first read only, based on the figures you provided. Not an audit or accounting opinion.',
    ar: 'الفحص المالي بالذكاء الاصطناعي. قراءة أولية فقط بناءً على الأرقام التي قدّمتها، وليست رأياً محاسبياً أو تقرير تدقيق.',
  },
}

const TERM: ToolCopy = {
  title: { en: AI_TOOL_NAMES.term_sheet_review, ar: 'مراجعة ورقة الشروط' },
  banner: {
    en: 'An AI read of a term sheet. It flags terms that look unusual compared with common market practice so you know what to ask. It is not legal or investment advice.',
    ar: 'قراءة بالذكاء الاصطناعي لورقة الشروط. تُبرز البنود التي تبدو غير مألوفة مقارنة بالممارسات الشائعة في السوق لتعرف ما تسأل عنه. ليست استشارة قانونية أو استثمارية.',
  },
  will: [
    'Summarise the key terms in plain words.',
    'Flag terms that look unusual against general market practice.',
    'Suggest questions for your lawyer.',
  ],
  willNot: [
    'Tell you whether to sign, invest or negotiate a term.',
    'Give a legal opinion or check enforceability under any law.',
  ],
  consentLead: {
    en: 'I am allowed to share this term sheet, including under any confidentiality obligation, and I will not upload a listed company\'s non-public information.',
    ar: 'يحق لي مشاركة ورقة الشروط هذه، بما في ذلك وفق أي التزام بالسرية، ولن أرفع أي معلومات غير معلنة لشركة مدرجة.',
  },
  footerLead: {
    en: 'Term sheet review. "Market practice" means general patterns in public sources, not a legal opinion or a view on whether to invest.',
    ar: 'مراجعة ورقة الشروط. يُقصد بـ"ممارسات السوق" الأنماط العامة في المصادر المتاحة، وليست رأياً قانونياً أو رأياً بشأن الاستثمار.',
  },
}

const PRICING: ToolCopy = {
  title: { en: AI_TOOL_NAMES.pricing_sense_check, ar: 'التحقق الأولي من التقييم' },
  banner: {
    en: 'An AI comparison of an asking price with public comparables and reported regional deals. It is a sense-check for your own thinking, not a price opinion, fairness opinion or investment advice.',
    ar: 'مقارنة بالذكاء الاصطناعي بين التقييم المطلوب وشركات مماثلة معلنة وصفقات إقليمية منشورة. هي أداة للتحقق الأولي لتفكيرك، وليست تقييماً أو رأياً بعدالة السعر أو استشارة استثمارية.',
  },
  will: [
    'Compare the asking figure with public comparables and reported regional deals.',
    'Show the ranges and sources it used.',
    'Note the main gaps in the comparison.',
  ],
  willNot: [
    'Give a price opinion, price target or fairness opinion.',
    'Say whether a price is right or whether to invest.',
    'Use private deal data or non-public information.',
  ],
  consentLead: {
    en: 'I understand this is not a price opinion by a Taqeem-accredited valuer or a CMA-authorised person, and I will not rely on it to price, buy or sell any security.',
    ar: 'أُدرك أن هذا ليس تقييماً صادراً عن مقيّم معتمد من الهيئة السعودية للمقيّمين المعتمدين (تقييم) أو عن شخص مرخّص من هيئة السوق المالية، ولن أعتمد عليه في تسعير أي ورقة مالية أو شرائها أو بيعها.',
  },
  footerLead: {
    en: 'Pricing sense-check. Comparables and deal data come from public sources and may be incomplete or stale. Not a price opinion or investment recommendation.',
    ar: 'التحقق الأولي من التقييم. بيانات الشركات المماثلة والصفقات مأخوذة من مصادر عامة وقد تكون ناقصة أو قديمة. ليس تقييماً ولا توصية استثمارية.',
  },
}

const MARKET: ToolCopy = {
  title: { en: AI_TOOL_NAMES.market_brief, ar: 'موجز دخول السوق السعودي' },
  banner: {
    en: 'An AI brief on entering the Saudi market: licences, local partner rules, Saudization and incentives, from public sources. Rules change often. It is not legal or tax advice.',
    ar: 'موجز بالذكاء الاصطناعي عن دخول السوق السعودي: التراخيص وقواعد الشريك المحلي والتوطين والحوافز، من مصادر عامة. تتغير الأنظمة كثيراً. ليس استشارة قانونية أو ضريبية.',
  },
  will: [
    'Outline common licences, foreign ownership and local partner points, Saudization (Nitaqat) and incentives for your sector.',
    'Link the public sources it used.',
    'List questions for a Saudi lawyer and MISA.',
  ],
  willNot: [
    'Confirm what applies to your specific case.',
    'Replace a licensed Saudi lawyer, tax adviser or the relevant government authority.',
  ],
  consentLead: {
    en: 'I understand Saudi rules change often and this brief may be out of date, and I will confirm requirements with a licensed Saudi lawyer and the relevant authority.',
    ar: 'أُدرك أن الأنظمة السعودية تتغير كثيراً وأن هذا الموجز قد يكون غير محدّث، وسأتحقق من المتطلبات مع محامٍ سعودي مرخّص والجهة الحكومية المختصة.',
  },
  footerLead: {
    en: 'Saudi market entry brief. Based on public sources as at [DATE]. Confirm current rules with a licensed Saudi lawyer and the relevant authority.',
    ar: 'موجز دخول السوق السعودي. مبني على مصادر عامة حتى تاريخ [DATE]. تحقّق من الأنظمة السارية مع محامٍ سعودي مرخّص والجهة المختصة.',
  },
}

const TOOLS: Record<AiToolKey, ToolCopy> = {
  cfo_check: CFO,
  market_brief: MARKET,
  term_sheet_review: TERM,
  pricing_sense_check: PRICING,
}

export const AI_TOOL_CARD_LINES: Record<AiToolKey, string> = {
  cfo_check: 'A first read of accounts or a model. Not accounting or audit.',
  market_brief: 'A sourced brief on entering the Saudi market. Not legal or tax advice.',
  term_sheet_review: 'A read of a term sheet against common market practice. Not legal advice.',
  pricing_sense_check: 'A comparison with public comparables. General and educational only.',
}

export const AI_TOOL_CARD_LINES_AR: Record<AiToolKey, string> = {
  cfo_check: 'قراءة أولى للحسابات أو النموذج. ليست محاسبة أو تدقيقاً.',
  market_brief: 'موجز عن دخول السوق السعودي. ليست استشارة قانونية أو ضريبية.',
  term_sheet_review: 'قراءة لورقة الشروط مقابل الممارسة الشائعة. ليست استشارة قانونية.',
  pricing_sense_check: 'مقارنة مع بيانات معلنة. للتعليم العام فقط.',
}

export function toolTitle(tool: AiToolKey, lang: 'en' | 'ar'): string {
  return TOOLS[tool].title[lang]
}

export type LegalSlots = {
  entity: string
  cr: string
  provider: string
  privacy: string
  terms: string
  retentionDays: number
  date: string
}

export function fillLegal(text: string, slots: LegalSlots): string {
  return text
    .split('[BA ENTITY]').join(slots.entity)
    .split('[CR]').join(slots.cr)
    .split('[AI PROVIDER]').join(slots.provider)
    .split('[PRIVACY LINK]').join(slots.privacy)
    .split('[TERMS LINK]').join(slots.terms)
    .split('[RETENTION DAYS]').join(String(slots.retentionDays))
    .split('[DATE]').join(slots.date)
}

export type RenderedToolCopy = {
  title: string
  banner: string
  will: readonly string[]
  willNot: readonly string[]
  consent: string
  footerLead: string
  footerShared: string
  footer: string
}

export function renderToolCopy(tool: AiToolKey, lang: Lang, slots: LegalSlots): RenderedToolCopy {
  const block = TOOLS[tool]
  const lead = fillLegal(block.consentLead[lang], slots)
  const core = fillLegal(SHARED_CONSENT[lang], slots)
  const footerLead = fillLegal(block.footerLead[lang], slots)
  const footerShared = fillLegal(SHARED_FOOTER[lang], slots)
  return {
    title: block.title[lang],
    banner: fillLegal(block.banner[lang], slots),
    will: block.will,
    willNot: [...block.willNot, ...SHARED_WILL_NOT],
    consent: `${lead} ${core}`,
    footerLead,
    footerShared,
    footer: `${footerLead} ${footerShared}`,
  }
}

export function toolCopySource(tool: AiToolKey): ToolCopy {
  return TOOLS[tool]
}
